### ISSUE TITLE
View the key in pending status

### ISSUE THREAD

**Issue by lixianbin1** [PolymeshAssociation/polymesh-sdk#887]
Assign a key to my Polymesh Account，but，What should I do if I want to check the keys I have invited，I didn't find the API for this query
![image](https://user-images.githubusercontent.com/22391220/201617022-1f66aeb9-9c84-4ecf-8736-9ea6bfd5cbb4.png)

**Comment by lixianbin1** [comment]
Okay, I found it

**Comment by F-OBrien** [comment]
@lixianbin1 Glad you got your issue resolved. For reference if using Polymaths dashboard to add secondary keys then the easiest way to accept joining the identity is to select the secondary key in your wallet to make it active and then go back to the account tab of the dashboard. A banner will display at the top of the dashboard window with an option to confirm joining the secondary key to the identity.

There are also multiple other options available. Some are listed below:

If using the Polkadot API you can use the identity pallet - `authorizations` to get a list of pending authorization ID's. See this link for available extrinsics and chain state https://polymesh.subscan.io/runtime/Identity?version=5001002

You can use the Polymesh instance of the Polkadot JS app to similarly query the chain to get an authorization ID
https://testnet-app.polymesh.live/#/chainstate
or 
https://mainnet-app.polymesh.network/#/chainstate
![image](https://user-images.githubusercontent.com/42175565/201627914-0b194b58-c514-4e58-a7f3-a38b2d3253df.png)

Or you can just look at the event from one of the authorizations you created to get the authorization ID. e.g. https://polymesh-testnet.subscan.io/extrinsic/5760178-1?event=5760178-1

If using the SDK you can use [getAccount](https://github.com/PolymeshAssociation/polymesh-sdk/wiki/api.client.AccountManagement.AccountManagement#getaccount) to get the account [authorizations](https://github.com/PolymeshAssociation/polymesh-sdk/wiki/api.entities.Account.Account#authorizations) and [getReceived](https://github.com/PolymeshAssociation/polymesh-sdk/wiki/api.entities.common.namespaces.Authorizations.Authorizations#getreceived) to return a list of [Authorizations Requests](https://github.com/PolymeshAssociation/polymesh-sdk/wiki/api.entities.AuthorizationRequest.AuthorizationRequest).
