### ISSUE TITLE
Expected input with 32 bytes (256 bits), found 31 bytes

### ISSUE THREAD

**Issue by lixianbin1** [PolymeshAssociation/polymesh-sdk#889]
I am using ` assets. compliance. requirements CheckSettle()` ,The compliance check was performed, but an error was reported. I passed the value according to the parameters in the wiki, but it was wrong. I used `did` and `Identity`, but they all prompted me with errors

```
//......
const assets = await this.api.assets.getAsset({
    ticker:"LXB"
});
const checkSettle = await assets.compliance.requirements.checkSettle({
    // from:leg.from.owner,
    to:leg.to.owner,
})
```

**Comment by lixianbin1** [comment]
I tried to use `assets.settlements.canTransfer`, but there is a problem. If A has AICE assets and has issued 600 tokens, and then he transfers them to B 500 tokens, then when B calls `assets.settlements.canTransfer` to check, the dashboard will prompt that the balance is insufficient, because AICE 500 tokens have been locked and cannot be created again, but A has enough balance to pay, and B can `accept()`, I think this method is used when creating transfer assets. What if I want to check the settlement information at the receiver?

**Comment by F-OBrien** [comment]
What you have stated is the described behavior of `canTransfer` per the documentation.
See https://github.com/PolymeshAssociation/polymesh-sdk/wiki/api.entities.Asset.Settlements.Settlements#cantransfer

**Comment by F-OBrien** [comment]
> I am using ` assets. compliance. requirements CheckSettle()` ,The compliance check was performed, but an error was reported. I passed the value according to the parameters in the wiki, but it was wrong. I used `did` and `Identity`, but they all prompted me with errors
> 
> ```
> //......
> const assets = await this.api.assets.getAsset({
>     ticker:"LXB"
> });
> const checkSettle = await assets.compliance.requirements.checkSettle({
>     // from:leg.from.owner,
>     to:leg.to.owner,
> })
> ```

Thanks for bringing this to our attention. We have replicated your issue and we will investigate.

**Comment by F-OBrien** [comment]
@lixianbin1 as per above you will see Eric has proposed a fix for the type issue with `canSettle`. You also likely noticed `canSettle` is marked as deprecated with the suggestion to use `canTransfer` instead so we would recommend against its use going forward. 

The issue you highlighted with `canTransfer` on already affirmed settlement legs is as it is intended to behave. `canTransfer` is primarily used before affirming a settlement instructions and considers free balance in addition to compliance rules. i.e. if you want to transfer an additional 500 tokens but you didn't have enough free balance it should correctly fail even if you had a balance greater than 500 when counting locked and unlocked tokens. 

If you want to verify compliance requirements for an already affirmed instruction, e.g. prior to finalizing the last leg of the settlement instruction, you can still use `canTransfer` but you should set the amount to 0 (or less than the available free balance).
```
const canTransferResult = await myAsset.settlements.canTransfer({
  from: account1,
  to: account2,
  amount: new BigNumber(0),
});
```

**Comment by lixianbin1** [comment]
@F-OBrien OK, thank you very much for your help.
