### ISSUE TITLE
Something is wrong with my account

### ISSUE THREAD

**Issue by lixianbin1** [PolymeshAssociation/polymesh-sdk#894]
I did some operations on the test website. I forgot what I did, but it was obvious that there was a problem with this account. It could find out the identity, but it was not in the auxiliary list of this identity

![image](https://user-images.githubusercontent.com/22391220/204235664-688e5e6a-7451-4fd6-96a4-30abdf57047b.png)

Its address is 5GHLdXEBiXbjGcd7RjGZN529vq1bbj6EkzV4Hai2Rvdd16Qj

**Comment by F-OBrien** [comment]
What is your issue? This account is a multisig signer for multisig account 5DCJTxZBof4pGsue38aPsiegCyQegCC8jKyHpPMiZNfiZKwE.
Signers are not attached to an identity they are attached to a multisig.
https://polymesh-testnet.subscan.io/account/5GHLdXEBiXbjGcd7RjGZN529vq1bbj6EkzV4Hai2Rvdd16Qj

**Comment by lixianbin1** [comment]
Oh, I see. The test network account list does not display multi signature accounts. I thought it would display all accounts related to identity. Thank you
